export const slides = [
  {
    id: '1',
    title: 'Welcome to Your Hairlytics',
    description: 'Fresh fades, sharp styles — your perfect look starts here',
    image: require('../../assets/images/salonwelcome.png'),
  },
  {
    id: '2',
    title: 'Salon- Quality at Home',
    description: 'Relax where you are — we’ll bring the grooming to you',
    image: require('../../assets/images/salonhome.png'),
  },
  {
    id: '3',
    title: 'Explore Premium Services',
    description: 'Haircuts, facials, massages — all just a tap away.',
    image: require('../../assets/images/salonservice.png'),
  },
  {
    id: '4',
    title: 'Book Appointments Instantly',
    description: 'No more waiting. Book your appointment anytime, anywhere.',
    image: require('../../assets/images/salonbook.png'),
  },
  {
    id: '5',
    title: 'Grow Your Barber Business Online',
    description: 'Get bookings, showcase your services, and boost your income.',
    image: require('../../assets/images/salonshop.png'),
  },
  {
    id: '6',
    title: 'Flexible & Secure Payments',
    description: 'Cash or online — pay how you like, with full confidence',
    image: require('../../assets/images/salonpay.png'),
  },
];

export const DATA = [
  'Barber Shop',
  'Hair Cut',
  'Facial',
  'Massage',
  'Beard Trim',
  'Hair Coloring',
  'Spa',
  'Pedicure',
  'Manicure',
  'Head Massage',
  'Body Massage',
  'Shaving',
  'Hair Wash',
  'Hair Styling',
  'Hair Spa',
  'Nail Art',
  'Skin Treatment',
  'Waxing',
  'Threading',
  'Makeup',
  'Bridal Makeup',
  'Party Makeup',
  'Foot Massage',
  'Shoulder Massage',
  'Back Massage',
  'Hair Straightening',
  'Hair Curling',
  'Beard Styling',
  'Hot Towel Shave',
  'Detox Facial',
  'Luxury Spa',
  'Ayurvedic Massage',
  'Oil Massage',
  'Kids Haircut',
  'Men’s Grooming',
  'Women’s Grooming',
  'Anti-dandruff Treatment',
  'Keratin Treatment',
  'Hair Extensions',
  'Scalp Massage',
  'Gold Facial',
  'Diamond Facial',
  'Fruit Facial',
  'Oxygen Facial',
  'Anti-aging Facial',
  'Body Scrub',
  'Full Body Spa',
  'Thai Massage',
  'Swedish Massage',
  'Deep Tissue Massage',
  'Head Spa',
  'Foot Spa',
  'Hair Smoothening',
  'Hair Rebonding',
  'Hair Botox',
  'Shampoo & Conditioner',
  'Eyebrow Shaping',
  'Eyelash Extension',
  'Mehndi Design',
  'Tattoo Service',
  'Beard Coloring',
  'Hair Highlights',
  'Hair Low Lights',
  'Hair Balayage',
  'Hair Gloss',
  'Hair Toner',
  'Hair Mask',
  'Scalp Detox',
  'Hand Massage',
  'Nail Extension',
  'French Manicure',
  'Gel Manicure',
  'Classic Pedicure',
  'Spa Pedicure',
  'Foot Scrub',
  'Callus Removal',
  'Nail Polish',
  'Gel Polish',
  'Nail Repair',
  'Body Wrap',
  'Whitening Facial',
  'De-tan Treatment',
  'Acne Treatment',
  'Hair Fall Treatment',
  'Scalp Treatment',
  'Aromatherapy',
  'Hot Stone Massage',
  'Balinese Massage',
  'Body Polishing',
  'Hair Cut for Women',
  'Hair Cut for Men',
  'Hair Cut for Kids',
  'Quick Trim',
  'Buzz Cut',
  'Crew Cut',
  'Layer Cut',
  'Bob Cut',
  'Pixie Cut',
  'Fringe Cut',
  'Step Cut',
  'U-Cut',
  'V-Cut',
  'Feather Cut',
  'Shag Cut',
  'Fade Cut',
  'Undercut',
  'Pompadour',
  'Quiff Style',
  'Mohawk Style',
  'Spiky Hair',
  'Slick Back',
  'Messy Style',
  'Curly Styling',
  'Straight Styling',
  'Blow Dry',
  'Hair Ironing',
  'Hair Crimping',
  'Temporary Hair Color',
  'Permanent Hair Color',
  'Root Touch Up',
  'Global Hair Color',
  'Fashion Hair Color',
  'Ombre Hair Color',
  'Hair Bleaching',
  'Henna Application',
  'Hair Spa Treatment',
  'Protein Treatment',
  'Smooth Hair Treatment',
  'Split End Removal',
  'Hair Shine Treatment',
  'Hair Volume Treatment',
  'Hair Density Booster',
  'Scalp Nourishment',
  'Hair Oil Therapy',
  'Relaxing Massage',
  'Couple Spa',
  'Luxury Pedicure',
  'Luxury Manicure',
  'Body Relaxation',
  'Glow Facial',
  'Hydrating Facial',
  'Brightening Facial',
  'Charcoal Facial',
  'Peel Off Mask',
  'Mud Mask',
  'Aloe Vera Treatment',
  'Cucumber Facial',
  'Skin Brightening',
  'Skin Hydration',
  'Skin Glow Treatment',
  'Skin Rejuvenation',
  'Skin Whitening',
  'Skin Polishing',
  'Skin Cleanup',
  'Body Whitening',
  'Back Facial',
  'Hand Facial',
  'Neck Massage',
  'Shoulder Therapy',
  'Slimming Massage',
  'Stretch Massage',
  'Reflexology',
  'Foot Reflexology',
  'Hand Reflexology',
  'Head Reflexology',
  'Ear Candling',
  'Body Relaxation Pack',
  'Signature Spa',
  'Luxury Grooming Pack',
  'Men’s Shaving Pack',
  'Bridal Grooming Pack',
  'Party Grooming Pack',
  'Royal Spa Pack',
  'Herbal Spa Pack',
  'Detox Spa Pack',
  'Body Glow Pack',
  'Wedding Package',
  'Engagement Package',
  'Festival Grooming Pack',
  'Salon Deluxe Pack',
  'Hair & Skin Combo',
  'Full Grooming Combo',
  'VIP Spa Package',
  'Premium Haircut',
  'Express Haircut',
  'Classic Haircut',
  'Luxury Haircut',
  'Beard Grooming Combo',
  'Hair Spa Combo',
  'Skin Glow Combo',
  'Detox Combo',
  'Massage Combo',
  'Relax Combo',
  'Beauty & Spa Package',
];

export const barberDashboardData = [
  {
    id: 1,
    title: "Today's Appointments",
    value: 12,
    color: '#4F46E5',
    icon: 'calendar',
  },
  {
    id: 2,
    title: 'Completed Appointments',
    value: 8,
    color: '#22C55E',
    icon: 'checkmark-done',
  },
  {
    id: 3,
    title: 'Pending Appointments',
    value: 4,
    color: '#F59E0B',
    icon: 'time',
  },
  {
    id: 4,
    title: 'Total Revenue',
    value: '₹ 4,500',
    color: '#EF4444',
    icon: 'cash',
  },
];
